all:
	javac -encoding UTF-8 Hello.java -classpath "../.."
	javac -encoding UTF-8 Frequencer.java -classpath "../.."
	javac -encoding UTF-8 InformationEstimator.java -classpath "../.."
	javac -encoding UTF-8 TestCase.java -classpath "../.."
	javac -encoding UTF-8 FinalTest.java -classpath "../.."
run:
#	java -classpath "../.." s4.B171836/Hello
#	java -classpath "../.." s4.B171836/Frequencer
#	java -classpath "../.." s4.B171836/InformationEstimator
#	java -classpath "../.." s4.B171836/TestCase
#	java -classpath "../.." s4.B171836/FinalTest
